---
title: "strings_and_factors"
output: html_document
date: "2022-10-18"
---
# Loading library
```{r}
library(tidyverse)
library(rvest)
library(p8105.datasets)
```

```{r}
string_vec = c("my", "name", "is", "jeff")

str_detect(string_vec, "jeff")
# str_detect is to find the thing you are looking for even a lettter.

str_replace(string_vec, "jeff", "Jeff")
# str_replace(dataframe, "the thing you want to replace","after replace")

```


```{r}
string_vec = c(
  "i think we all rule for participating",
  "i think i have been caught",
  "i think this will be quite fun actually",
  "it will be fun, i think"
  )

str_detect(string_vec, "^i think")
# ^:begin with I think
str_detect(string_vec, "i think$")
# i think$: end up with I think
```

```{r}
string_vec = c(
  "Y'all remember Pres. HW Bush?",
  "I saw a green bush",
  "BBQ and Bushwalking at Molonglo Gorge",
  "BUSH -- LIVE IN CONCERT!!"
  )

str_detect(string_vec,"[Bb]ush")
# []: you can accept both of them in this []
```

```{r}
string_vec = c(
  '7th inning stretch',
  '1st half soon to begin. Texas won the toss.',
  'she is 5 feet 4 inches tall',
  '3AM - cant sleep :('
  )

str_detect(string_vec, "^[0-9][a-zA-Z]")
# from 0-9 and a-z and A-Z
```


```{r}
string_vec = c(
  'Its 7:11 in the evening',
  'want to go to 7-11?',
  'my flight is AA711',
  'NetBios: scanning ip 203.167.114.66'
  )

str_detect(string_vec, "7.11")
# 7 separate with 11
```

```{r}
string_vec = c(
  'The CI is [2, 5]',
  ':-]',
  ':-[',
  'I found the answer on pages [6-7]'
  )

str_detect(string_vec, "\\[")
# \\: seaerch for [
str_detect(string_vec, "\\[[0-9]")
```

# Why factors are weird
```{r}
vec_sex = factor(c("male", "male", "female", "female"))
as.numeric(vec_sex)
vec_sex = fct_relevel(vec_sex, "male")
# factor relevel change male before female
```

#NSDUH
```{r}
nsduh_url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

table_marj = 
  read_html(nsduh_url) %>% 
  html_table() %>% 
  first() %>%
  slice(-1)
table_marj %>% view
```

# tidy up the NSDUH data...
```{r}
data_marj = 
  table_marj %>%
  select(-contains("P Value")) %>%
    pivot_longer(
    -State,
    names_to = "age_year", 
    values_to = "percent") %>%
  separate(age_year, into = c("age", "year"), sep = "\\(") %>%   mutate(year = str_replace(year, "\\)", ""),
    percent = str_replace(percent, "[a-b]$",""),
         percent = as.numeric(percent)) %>% 
  filter(!(State %in% c("Total U.S.", "Northeast", "Midwest", "South", "West","District of Columbia")))

  
# pivot everything except State. ! take opposite
```

```{r}
data_marj %>%
  filter(age == "12-17") %>% 
  mutate(State = fct_reorder(State, percent)) %>% 
  ggplot(aes(x = State, y = percent, color = year)) + 
    geom_point() + 
    theme(axis.text.x = element_text(angle = 90, hjust = 1))
# reorder the state variable with the percent of them, so we can use in ggplot
```

```{r}

```

